name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  # Pagesデプロイに必要な権限（push時のdeployで使う）
  contents: read
  pages: write
  id-token: write

jobs:
  # 1) テストだけ行うジョブ
  test:
    name: Test (both PR and push)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # 2) mainブランチへのpush時にのみビルド＆Pagesデプロイを行うジョブ
  build_and_deploy:
    name: Build and Deploy to GitHub Pages
    needs: [test]  # テストジョブに成功してから続行
    runs-on: ubuntu-latest
    # pull_requestではなく、mainブランチにpushされた時だけ実行
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Webpack等のビルド成果物がpublic/に出力される想定
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
