name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build for Production
        run: npm run build
      
      - name: Build Docker image (Optional)
        # Dockerを利用する場合に実行
        run: |
          docker build -t silent-arcana .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for Production
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # gh-pagesブランチを作成
          git checkout --orphan gh-pages
          git rm -rf .
          # publicディレクトリをコピー（bundle.js含む）
          cp -r public/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
